apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-platform-ui
  namespace: argocd             
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rajatayyab-lab/eks-manifest.git
    targetRevision: test
    path: k8s-cluster 
  destination:
    server: https://kubernetes.default.svc
    namespace: apps 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true            
    syncOptions:
      - CreateNamespace=true